[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311Full"]

[build.nixpacksPlan.phases.install]
cmds = ["python3 -m pip install -r api/requirements.txt"]

[start]
cmd = "gunicorn app:app --chdir api --bind 0.0.0.0:$PORT"
