[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311"]  # ✅ includes pip automatically

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r api/requirements.txt"]

[start]
cmd = "gunicorn app:app --chdir api --bind 0.0.0.0:$PORT"
